### ISSUE TITLE
raspberry pie zero

### ISSUE THREAD

**Issue by shaul75** [Legion2/CorsairLightingProtocol#174]
any plans to port this to Raspbian?

**Comment by Legion2** [comment]
The purpose of this library is to create DIY devices which are detected and controlled via iCUE. The arduino platform is very well suited for that because the devices are minimal and cheap. Raspbian is an OS which has much more power and so much capabilities not needed for an LED controller. I don't see the benefit of supporting Raspbian/Linux.

Supporting the corsair HID protocol on other platforms may be useful for some use cases, but therefore another project should be created with another codebase. For example for network based devices.
