### ISSUE TITLE
Сan't rotate and reorder fans in iCUE

### ISSUE THREAD

**Issue by AlivE-github** [Legion2/CorsairLightingProtocol#198]
Hello) Ask for help. I use 6 fans, everything works well, but in icue rotate and reorder fans does not have any effect. Is this how it should be, or am I doing something wrong?

(Powered By Google Translate :) )

**Comment by Legion2** [comment]
Rotate and reorder is something entirely done in iCUE, so it's only working in SoftwareLighting mode, not in hardware lighting mode. Because rotate and reorder is done in iCUE the arduino does not have to to anything special. iCUE changes the LED output which is interpreted by the arduino.

If rotate and reorder does not work it's more an iCUE problem because the arduino don't know about the rotation and order of the fans.
