### ISSUE TITLE
Any doubts

### ISSUE THREAD

**Issue by serlancelot** [Legion2/CorsairLightingProtocol#241]
Hello good morning, browsing the internet looking for something with arduino and Asus aura sync, I found your project, although I have a corsair power supply, I did not have ICUE installed but with your project I will put it quickly ...

Sorry for my clumsiness, I have several questions that I ask you below:

Is there a manual that explains what all the files in the example folder are for? (removing the ones with the corsair accessory name)

Regarding the commander PRO, do you have thought that 4 temperature probes, voltages and the power to control the fans with ICUE can be displayed? Is it easy to make that modification?

Thanks for everything!!

**Comment by Legion2** [comment]
In the example folder are Arduino Projects which demonstrate the usage of this library. There are also files which are only needed internally by this library for testing and development (you can ignore them).

If you connect some kind of display to the arduino, you can display any information of the Commander PRO, including temperature probes connected to the arduino, voltage measured by the arduino and fan power of fans connected to the arduino. You can not display information such as CPU Temp because iCUE does not send this to the Commander PRO.
