### ISSUE TITLE
Corsair iCUE LS100 Smart Lighting Strip support

### ISSUE THREAD

**Issue by Comango104** [Legion2/CorsairLightingProtocol#65]
Assuming it uses a ATmega32U4, what would you require to make this possible?
Would love to be able to make a cheap version of this controller.

**Comment by McHauge** [comment]
I made this hardware and have used it in my pc for about a month now, the total cost per unit was around 7-10% (bought 10 at once since that's the lowest that makes sense), with both PCB and components ordered directly from china in one go. It's schematic is based around the Arduino Leonardo.

It's also using the ATmega32u4 and the software from here, so with a quick software update and it should be good to go. 

[OpenCorsairLighting](https://github.com/McHauge/OpenCorsairLighting)

![IMG_20191028_135318](https://user-images.githubusercontent.com/31018035/69156263-72e9cb80-0ae3-11ea-969d-448b8a5155b2.jpg)
![IMG_20191028_160634](https://user-images.githubusercontent.com/31018035/69156284-77ae7f80-0ae3-11ea-8386-f16e7040290d.jpg)
![IMG_20191101_133956](https://user-images.githubusercontent.com/31018035/69156310-7e3cf700-0ae3-11ea-9c12-68b710bd1007.jpg)

**Comment by Legion2** [comment]
I need the USB PID of SP100 and if it uses the same protocol as the Lighting Node PRO it should work.

**Comment by Legion2** [comment]
I was able to find the ids of the LS100 see [wiki](https://github.com/Legion2/CorsairLightingProtocol/wiki/How-to-use-Corsair-fans-or-other-hardware#rgb-controller). Now i will try to get the LS100 working.

**Comment by Comango104** [comment]
> I made this hardware and have used it in my pc for about a month now, the total cost per unit was around 7-10% (bought 10 at once since that's the lowest that makes sense), with both PCB and components ordered directly from china in one go. It's schematic is based around the Arduino Leonardo.
> 
> It's also using the ATmega32u4 and the software from here, so with a quick software update and it should be good to go.
> 
> [OpenCorsairLighting](https://github.com/McHauge/OpenCorsairLighting)
> 
> ![IMG_20191028_135318](https://user-images.githubusercontent.com/31018035/69156263-72e9cb80-0ae3-11ea-969d-448b8a5155b2.jpg)
> ![IMG_20191028_160634](https://user-images.githubusercontent.com/31018035/69156284-77ae7f80-0ae3-11ea-8386-f16e7040290d.jpg)
> ![IMG_20191101_133956](https://user-images.githubusercontent.com/31018035/69156310-7e3cf700-0ae3-11ea-9c12-68b710bd1007.jpg)

Wow that's awesome, I'll definitely send some friends to your github page as well.

**Comment by Comango104** [comment]
> I was able to find the ids of the LS100 see [wiki](https://github.com/Legion2/CorsairLightingProtocol/wiki/How-to-use-Corsair-fans-or-other-hardware#rgb-controller). Now i will try to get the LS100 working.

Wow that was fast! Thanks Legion. <3 I've been looking for a ambient lighting solution for a while now and for the price of some ws2812 strips, a powersupply and a ATmega32U4 MCU with proper control software this is perfect.

**Comment by Legion2** [comment]
@Comango104 I also want to create an ambient lighting project. I created #68 so we can discuss ideas
